name: Deploy Multidocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t svenverbeek/demo-client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true svenverbeek/demo-client npm test

      - run: docker build -t svenverbeek/complex:client ./client
      - run: docker build -t svenverbeek/complex:server ./server
      - run: docker build -t svenverbeek/complex:worker ./worker
      - run: docker build -t svenverbeek/complex:nginx ./nginx

      - run: docker push svenverbeek/complex:client
      - run: docker push svenverbeek/complex:server
      - run: docker push svenverbeek/complex:worker
      - run: docker push svenverbeek/complex:nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-067460827288
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip