name: Deploy MultiK8s
on:
  push:
    branches:
       - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER.USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t svenverbeek/demo-client -f ./client/Dockerfile.dev ./client
          docker run -e CI=true svenverbeek/demo-client npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-396909

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
      
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-west4-a

      - name: Build
        run: |-
          docker build -t svenverbeek/complex-client:latest -t svenverbeek/complex-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t svenverbeek/complex-server:latest -t svenverbeek/complex-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t svenverbeek/complex-worker:latest -t svenverbeek/complex-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
      
      - name: Push
        run: |-
          docker push svenverbeek/complex-client:latest
          docker push svenverbeek/complex-server:latest
          docker push svenverbeek/complex-worker:latest

          docker push svenverbeek/complex-client:{{ env.SHA }}
          docker push svenverbeek/complex-server:{{ env.SHA }}
          docker push svenverbeek/complex-worker:{{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=svenverbeek/complex-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=svenverbeek/complex-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=svenverbeek/complex-worker:${{ env.SHA }}